#!/bin/bash

cd /home/ngenebio/gatk-workflows/cromwell-executions/myWorkflow/b71073e9-0381-4f42-a943-1483dfff115e/call-myTask/execution
tmpDir=$(mkdir -p "/home/ngenebio/gatk-workflows/cromwell-executions/myWorkflow/b71073e9-0381-4f42-a943-1483dfff115e/call-myTask/tmp.65281b97" && echo "/home/ngenebio/gatk-workflows/cromwell-executions/myWorkflow/b71073e9-0381-4f42-a943-1483dfff115e/call-myTask/tmp.65281b97")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /home/ngenebio/gatk-workflows/cromwell-executions/myWorkflow/b71073e9-0381-4f42-a943-1483dfff115e/call-myTask/execution

)
outb71073e9="${tmpDir}/out.$$" errb71073e9="${tmpDir}/err.$$"
mkfifo "$outb71073e9" "$errb71073e9"
trap 'rm "$outb71073e9" "$errb71073e9"' EXIT
tee '/home/ngenebio/gatk-workflows/cromwell-executions/myWorkflow/b71073e9-0381-4f42-a943-1483dfff115e/call-myTask/execution/stdout' < "$outb71073e9" &
tee '/home/ngenebio/gatk-workflows/cromwell-executions/myWorkflow/b71073e9-0381-4f42-a943-1483dfff115e/call-myTask/execution/stderr' < "$errb71073e9" >&2 &
(
cd /home/ngenebio/gatk-workflows/cromwell-executions/myWorkflow/b71073e9-0381-4f42-a943-1483dfff115e/call-myTask/execution


echo "hello world"
sleep 10
uname -a
)  > "$outb71073e9" 2> "$errb71073e9"
echo $? > /home/ngenebio/gatk-workflows/cromwell-executions/myWorkflow/b71073e9-0381-4f42-a943-1483dfff115e/call-myTask/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /home/ngenebio/gatk-workflows/cromwell-executions/myWorkflow/b71073e9-0381-4f42-a943-1483dfff115e/call-myTask/execution
find . -type d -empty -print0 | xargs -0 -I % touch %/.file
)
(
cd /home/ngenebio/gatk-workflows/cromwell-executions/myWorkflow/b71073e9-0381-4f42-a943-1483dfff115e/call-myTask/execution
sync


)
mv /home/ngenebio/gatk-workflows/cromwell-executions/myWorkflow/b71073e9-0381-4f42-a943-1483dfff115e/call-myTask/execution/rc.tmp /home/ngenebio/gatk-workflows/cromwell-executions/myWorkflow/b71073e9-0381-4f42-a943-1483dfff115e/call-myTask/execution/rc
