#!/bin/bash

cd /home/ngenebio/gatk-workflows/cromwell-executions/myWorkflow/ed745524-07b6-49ce-8473-652694b2b973/call-myTask/execution
tmpDir=$(mkdir -p "/home/ngenebio/gatk-workflows/cromwell-executions/myWorkflow/ed745524-07b6-49ce-8473-652694b2b973/call-myTask/tmp.85d7fa44" && echo "/home/ngenebio/gatk-workflows/cromwell-executions/myWorkflow/ed745524-07b6-49ce-8473-652694b2b973/call-myTask/tmp.85d7fa44")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /home/ngenebio/gatk-workflows/cromwell-executions/myWorkflow/ed745524-07b6-49ce-8473-652694b2b973/call-myTask/execution

)
outed745524="${tmpDir}/out.$$" erred745524="${tmpDir}/err.$$"
mkfifo "$outed745524" "$erred745524"
trap 'rm "$outed745524" "$erred745524"' EXIT
tee '/home/ngenebio/gatk-workflows/cromwell-executions/myWorkflow/ed745524-07b6-49ce-8473-652694b2b973/call-myTask/execution/stdout' < "$outed745524" &
tee '/home/ngenebio/gatk-workflows/cromwell-executions/myWorkflow/ed745524-07b6-49ce-8473-652694b2b973/call-myTask/execution/stderr' < "$erred745524" >&2 &
(
cd /home/ngenebio/gatk-workflows/cromwell-executions/myWorkflow/ed745524-07b6-49ce-8473-652694b2b973/call-myTask/execution


echo "hello world"
sleep 10
uname -a
)  > "$outed745524" 2> "$erred745524"
echo $? > /home/ngenebio/gatk-workflows/cromwell-executions/myWorkflow/ed745524-07b6-49ce-8473-652694b2b973/call-myTask/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /home/ngenebio/gatk-workflows/cromwell-executions/myWorkflow/ed745524-07b6-49ce-8473-652694b2b973/call-myTask/execution
find . -type d -empty -print0 | xargs -0 -I % touch %/.file
)
(
cd /home/ngenebio/gatk-workflows/cromwell-executions/myWorkflow/ed745524-07b6-49ce-8473-652694b2b973/call-myTask/execution
sync


)
mv /home/ngenebio/gatk-workflows/cromwell-executions/myWorkflow/ed745524-07b6-49ce-8473-652694b2b973/call-myTask/execution/rc.tmp /home/ngenebio/gatk-workflows/cromwell-executions/myWorkflow/ed745524-07b6-49ce-8473-652694b2b973/call-myTask/execution/rc
