#!/bin/bash

cd /cromwell-executions/wf_hello/51c76c76-cc13-4e9b-82b9-a998d70ac801/call-hello/execution
tmpDir=$(mkdir -p "/cromwell-executions/wf_hello/51c76c76-cc13-4e9b-82b9-a998d70ac801/call-hello/tmp.c26c0910" && echo "/cromwell-executions/wf_hello/51c76c76-cc13-4e9b-82b9-a998d70ac801/call-hello/tmp.c26c0910")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/wf_hello/51c76c76-cc13-4e9b-82b9-a998d70ac801/call-hello/execution

)
out51c76c76="${tmpDir}/out.$$" err51c76c76="${tmpDir}/err.$$"
mkfifo "$out51c76c76" "$err51c76c76"
trap 'rm "$out51c76c76" "$err51c76c76"' EXIT
tee '/cromwell-executions/wf_hello/51c76c76-cc13-4e9b-82b9-a998d70ac801/call-hello/execution/stdout' < "$out51c76c76" &
tee '/cromwell-executions/wf_hello/51c76c76-cc13-4e9b-82b9-a998d70ac801/call-hello/execution/stderr' < "$err51c76c76" >&2 &
(
cd /cromwell-executions/wf_hello/51c76c76-cc13-4e9b-82b9-a998d70ac801/call-hello/execution


echo "Hello World! Welcome to Cromwell . . . on Google Cloud!"
)  > "$out51c76c76" 2> "$err51c76c76"
echo $? > /cromwell-executions/wf_hello/51c76c76-cc13-4e9b-82b9-a998d70ac801/call-hello/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/wf_hello/51c76c76-cc13-4e9b-82b9-a998d70ac801/call-hello/execution
find . -type d -empty -print0 | xargs -0 -I % touch %/.file
)
(
cd /cromwell-executions/wf_hello/51c76c76-cc13-4e9b-82b9-a998d70ac801/call-hello/execution
sync


)
mv /cromwell-executions/wf_hello/51c76c76-cc13-4e9b-82b9-a998d70ac801/call-hello/execution/rc.tmp /cromwell-executions/wf_hello/51c76c76-cc13-4e9b-82b9-a998d70ac801/call-hello/execution/rc
