#!/bin/bash

cd /home/ngenebio/gatk-workflows/cromwell-executions/myWorkflow/3d32c1ae-1d9c-4b2f-94d2-cd488fdf1d8b/call-myTask/execution
tmpDir=$(mkdir -p "/home/ngenebio/gatk-workflows/cromwell-executions/myWorkflow/3d32c1ae-1d9c-4b2f-94d2-cd488fdf1d8b/call-myTask/tmp.e66e2a4f" && echo "/home/ngenebio/gatk-workflows/cromwell-executions/myWorkflow/3d32c1ae-1d9c-4b2f-94d2-cd488fdf1d8b/call-myTask/tmp.e66e2a4f")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /home/ngenebio/gatk-workflows/cromwell-executions/myWorkflow/3d32c1ae-1d9c-4b2f-94d2-cd488fdf1d8b/call-myTask/execution

)
out3d32c1ae="${tmpDir}/out.$$" err3d32c1ae="${tmpDir}/err.$$"
mkfifo "$out3d32c1ae" "$err3d32c1ae"
trap 'rm "$out3d32c1ae" "$err3d32c1ae"' EXIT
tee '/home/ngenebio/gatk-workflows/cromwell-executions/myWorkflow/3d32c1ae-1d9c-4b2f-94d2-cd488fdf1d8b/call-myTask/execution/stdout' < "$out3d32c1ae" &
tee '/home/ngenebio/gatk-workflows/cromwell-executions/myWorkflow/3d32c1ae-1d9c-4b2f-94d2-cd488fdf1d8b/call-myTask/execution/stderr' < "$err3d32c1ae" >&2 &
(
cd /home/ngenebio/gatk-workflows/cromwell-executions/myWorkflow/3d32c1ae-1d9c-4b2f-94d2-cd488fdf1d8b/call-myTask/execution


echo "hello world"
sleep 10
uname -a
)  > "$out3d32c1ae" 2> "$err3d32c1ae"
echo $? > /home/ngenebio/gatk-workflows/cromwell-executions/myWorkflow/3d32c1ae-1d9c-4b2f-94d2-cd488fdf1d8b/call-myTask/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /home/ngenebio/gatk-workflows/cromwell-executions/myWorkflow/3d32c1ae-1d9c-4b2f-94d2-cd488fdf1d8b/call-myTask/execution
find . -type d -empty -print0 | xargs -0 -I % touch %/.file
)
(
cd /home/ngenebio/gatk-workflows/cromwell-executions/myWorkflow/3d32c1ae-1d9c-4b2f-94d2-cd488fdf1d8b/call-myTask/execution
sync


)
mv /home/ngenebio/gatk-workflows/cromwell-executions/myWorkflow/3d32c1ae-1d9c-4b2f-94d2-cd488fdf1d8b/call-myTask/execution/rc.tmp /home/ngenebio/gatk-workflows/cromwell-executions/myWorkflow/3d32c1ae-1d9c-4b2f-94d2-cd488fdf1d8b/call-myTask/execution/rc
