#!/bin/bash

cd /home/ngenebio/gatk-workflows/cromwell-executions/myWorkflow/dc9b456f-34ef-4b6b-bf72-08a48b548888/call-myTask/execution
tmpDir=$(mkdir -p "/home/ngenebio/gatk-workflows/cromwell-executions/myWorkflow/dc9b456f-34ef-4b6b-bf72-08a48b548888/call-myTask/tmp.2323bffc" && echo "/home/ngenebio/gatk-workflows/cromwell-executions/myWorkflow/dc9b456f-34ef-4b6b-bf72-08a48b548888/call-myTask/tmp.2323bffc")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /home/ngenebio/gatk-workflows/cromwell-executions/myWorkflow/dc9b456f-34ef-4b6b-bf72-08a48b548888/call-myTask/execution

)
outdc9b456f="${tmpDir}/out.$$" errdc9b456f="${tmpDir}/err.$$"
mkfifo "$outdc9b456f" "$errdc9b456f"
trap 'rm "$outdc9b456f" "$errdc9b456f"' EXIT
tee '/home/ngenebio/gatk-workflows/cromwell-executions/myWorkflow/dc9b456f-34ef-4b6b-bf72-08a48b548888/call-myTask/execution/stdout' < "$outdc9b456f" &
tee '/home/ngenebio/gatk-workflows/cromwell-executions/myWorkflow/dc9b456f-34ef-4b6b-bf72-08a48b548888/call-myTask/execution/stderr' < "$errdc9b456f" >&2 &
(
cd /home/ngenebio/gatk-workflows/cromwell-executions/myWorkflow/dc9b456f-34ef-4b6b-bf72-08a48b548888/call-myTask/execution


echo "hello world"
sleep 10
uname -a
)  > "$outdc9b456f" 2> "$errdc9b456f"
echo $? > /home/ngenebio/gatk-workflows/cromwell-executions/myWorkflow/dc9b456f-34ef-4b6b-bf72-08a48b548888/call-myTask/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /home/ngenebio/gatk-workflows/cromwell-executions/myWorkflow/dc9b456f-34ef-4b6b-bf72-08a48b548888/call-myTask/execution
find . -type d -empty -print0 | xargs -0 -I % touch %/.file
)
(
cd /home/ngenebio/gatk-workflows/cromwell-executions/myWorkflow/dc9b456f-34ef-4b6b-bf72-08a48b548888/call-myTask/execution
sync


)
mv /home/ngenebio/gatk-workflows/cromwell-executions/myWorkflow/dc9b456f-34ef-4b6b-bf72-08a48b548888/call-myTask/execution/rc.tmp /home/ngenebio/gatk-workflows/cromwell-executions/myWorkflow/dc9b456f-34ef-4b6b-bf72-08a48b548888/call-myTask/execution/rc
